# Site wide configuration

title: Inquisitor 
description: "A vangaurd for science"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: //phuicy.github.io/inquisitor

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Guy Burroughes
  web: http://localhost
  email: gburroughes1"gmail.com
  twitter: phuicy
  bio: "Enraged Roboticist."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
